# Generated by Django 4.2.4 on 2024-04-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categoryType',
            field=models.CharField(choices=[('M', 'Мясо'), ('F', 'Рыба')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Steak', max_length=128),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.category')),
                ('recipeThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeCategory',
            field=models.ManyToManyField(through='kitchen.RecipeCategory', to='kitchen.category'),
        ),
    ]
